### PR TITLE
Beelink GT1 Mini DTS file

### PR DESCRIPTION
**Pull request by pulento**
Beelink GT1 Mini DTS file. Basically the same as X96 Max but with an extra reserved memory so newer GT1 Mini-A model boots.

### CODE REVIEW

**Comment by 150balbes** [comment]
If not most of the code changes, you only need to change it. No need to duplicate the entire file. Use x96max as the primary source. You can see this in the x96max-rgmi example. The file name is better to specify as for the model gt1-mini-a (that would not be confusion with the version of gt1-mini)

https://github.com/150balbes/Amlogic_s905-kernel/blob/le/arch/arm64/boot/dts/amlogic/meson-g12a-x96-max-rmii.dts#L8

**Comment by pulento** [comment]
Done. Followed your recommendation and included x96-max as a base, renamed file too.

**Comment by 150balbes** [comment]
To ensure that these changes are not lost, I recommend sending them to the main kernel. For example, this mailing list. They can tell you how to arrange everything.

http://lists.infradead.org/mailman/listinfo/linux-amlogic

**Comment by pulento** [comment]
Sure. I'll try to upstream it.

Juanjo sin .sig :(

**Pull request merged**
